### ISSUE TITLE
AmigaOS4 : color issues in the game

### ISSUE THREAD

**Issue by kas1e** [ptitSeb/Eldritch#3]
Issues are that all in the game a bit "red" game and some wrong colors in fog which we discuss before

**Comment by ptitSeb** [comment]
It would have been easier with 3 separates tickets...

Anyway, for the EldritchSaveLoad_SaveMaster, where should it save if not on "./main.eldritchmastersave" ?

**Comment by kas1e** [comment]
"PROGDIR:.eldritch" imho will be find (there it usually we place all the games based data files like options and stuff). But it probabaly mean needs to create a directory .eldritch inside of main one, so maybe just put it all to root of game, i.e. "PROGDIR:main.edlritchmastersave" ?

**Comment by kas1e** [comment]
Will split issues in different tickets now, and that one we can keep for "colors" issue

**Comment by kas1e** [comment]
With removed swap, things not changes, but still works as before at least :)

**Comment by kas1e** [comment]
I think lately, maybe issues can be related to fragment shaders itself? Like, some endian conversion inside fragment shader needs to be done?

**Comment by kas1e** [comment]
I rebuild the whole game now with that last define disabled in color.h and it also didn't change anything (same all fine in the menu, and same "too red" in the game), so probably that ifdef can be removed too? Fewer ifdefs always better, code clean and in some parts faster too IMHO?

**Comment by ptitSeb** [comment]
Ok, I'll remove it

**Comment by kas1e** [comment]
Fixed with newer builds
